baseURL = 'https://openbracket.ca/'
languageCode = 'en-us'
title = 'Openbracket'
theme = 'dead-simple'

[[menu.main]]
name = "<u>H</u>ome"
url = "/"
weight = 1

[[menu.main]]
name = "<u>T</u>ags"
url = "/tags/"
weight = 2

[[menu.main]]
name = "Projects"
url = "/projects/"
weight = 3
