name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@2d028b70b5e397cf8314c6eaea229a6c3e34977a # v3.1.0
        with:
          host: 143.110.219.118
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ssh://root@143.110.219.118
      - name: Build and push
        uses: docker/build-push-action@v6
        env:
          DOCKER_HOST: ssh://root@143.110.219.118
        with:
          load: true
          tags: openbracket:latest
      - name: Update images
        run: ssh root@143.110.219.118 'cd /root/site && docker compose pull --ignore-pull-failures'
      - name: Restart Images
        run: ssh root@143.110.219.118 'cd /root/site && docker compose up -d --remove-orphans'
      - name: Prune old images
        run: ssh root@143.110.219.118 'cd /root/site && docker image prune'