name: ci

on:
  push:

jobs:
  buildx:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: MrSquaare/ssh-setup-action@2d028b70b5e397cf8314c6eaea229a6c3e34977a # v3.1.0
        with:
          host: ${{ secrets.SSH_HOST }}
          private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          private-key-name: openbrakcet
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          endpoint: ssh://root@${{ secrets.SSH_HOST }}